config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :buy_lists
  resources :feeds
  resources :family_members
  resources :families
  
  #root "inventory#index", :as => "inventory"
  get 'inventory', to: "inventory#index", :as =>'inventory'

  get 'buy_lists', to: "buy_list#index", :as =>'shopping'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get 'members', to: "member#index", :as => 'members'
  get 'feed', to: "feeds#index"
  #get 'new_shopping', to: "shopping#new"
  get 'new_inventory', to: "inventory#new"
  get 'inventory/:item_id/edit', to: "inventory#edit"
  #get 'new_member', to: "member#new"

  patch '/inventory/:item_id/edit', to: 'inventory#update'
  get 'family', to: "family#index"
  get 'members', to: "family_members#index", :as => 'members'
  resources :inventory
  # Defines the root path route ("/")
  root "landing#index"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  get "login", to: "sessions#new"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy_list.rb
class BuyList < ApplicationRecord
end

app/models/current.rb
# app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/family.rb
class Family < ApplicationRecord
    has_many :family_member
    has_many :inventory
end                                         

app/models/family_member.rb
class FamilyMember < ApplicationRecord
    belongs_to :families
    has_one :user
end

app/models/feed.rb
class Feed < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  
    has_secure_password
  
    before_save :downcase_email
  
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
    
    has_many :inventory
    has_many :shopping

    def confirm!
      update_columns(confirmed_at: Time.current)
    end
  
    def confirmed?
      confirmed_at.present?
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
  
    def unconfirmed?
      !confirmed?
    end
  
    private
  
    def downcase_email
      self.email = email.downcase
    end
  end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
    def index
        @shopping = Shopping.all
    end

    def new
        @shopping = Shopping.new
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_lists_helper.rb
module BuyListsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shopping/_form.html.erb
<%= form_with(model: @shopping) do |form| %>
  <% if shopping.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shopping.errors.count, "error") %> prohibited this shopping from being saved:</h2>

      <ul>
        <% shopping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :f_id, style: "display: block" %>
    <%= form.text_field :f_id , class: "form-control" %>
  </div>

  <div>
    <%= form.label :m_id, style: "display: block" %>
    <%= form.text_field :m_id , class: "form-control" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.text_field :dob, class: "form-control"  %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role, class: "form-control"  %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender, class: "form-control"  %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/shopping/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Shopping List</h1>
<div style="margin-bottom: 5px"><%= link_to "New Shopping List", new_shopping_path, class: "btn btn-primary"  %></div>
<div class="card" style="width: 18rem;">
  <div class="card-header">
Card title
  </div>
  <div class="card-body">
    <h5 class="card-title">Info</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">An item</li>
    <li class="list-group-item">A second item</li>
    <li class="list-group-item">A third item</li>
  </ul>
    <div class="card-footer">
    <button type="button" class="btn btn-success">Done</button>
    <button type="button" class="btn btn-warning">Edit</button>
    <button type="button" class="btn btn-danger">Danger</button>
  </div>
</div>






  <%
=begin%>
 <% @family_members.each do |family_member| %>

    <div style="margin-top: 1rem; border: 1px solid black; padding: 1.5rem; border-radius: 1.5rem">
    <%= render family_member %>
    <p>
      <%= link_to "Show", family_member, class: "btn btn-info"  %>
    </p>
    </div>
  <% end %>
 
<%
=end%>

app/views/shopping/new.html.erb
<h1>New Shopping List</h1>

<%= render "form", shopping: @shopping %>

<br>

<div>
  <%= link_to "Back to shopping list",shopping_path, class: "btn btn-secondary"  %>
</div>

app/views/shopping/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>