config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :buy_lists
  resources :feeds
  resources :family_members
  resources :families
  
  #root "inventory#index", :as => "inventory"
  get 'inventory', to: "inventory#index", :as =>'inventory'

  get 'buy_lists', to: "buy_list#index", :as =>'shopping'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get 'members', to: "member#index", :as => 'members'
  get 'feed', to: "feeds#index"
  #get 'new_shopping', to: "shopping#new"
  get 'new_inventory', to: "inventory#new"
  get 'inventory/:item_id/edit', to: "inventory#edit"
  #get 'new_member', to: "member#new"

  patch '/inventory/:item_id/edit', to: 'inventory#update'
  get 'family', to: "family#index"
  get 'members', to: "family_members#index", :as => 'members'
  resources :inventory
  # Defines the root path route ("/")
  root "landing#index"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  get "login", to: "sessions#new"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy_list.rb
class BuyList < ApplicationRecord
end

app/models/current.rb
# app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/family.rb
class Family < ApplicationRecord
    has_many :family_member
    has_many :inventory
end                                         

app/models/family_member.rb
class FamilyMember < ApplicationRecord
    belongs_to :families
    has_one :user
end

app/models/feed.rb
class Feed < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  
    has_secure_password
  
    before_save :downcase_email
  
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
    
    has_many :inventory
    has_many :shopping

    def confirm!
      update_columns(confirmed_at: Time.current)
    end
  
    def confirmed?
      confirmed_at.present?
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
  
    def unconfirmed?
      !confirmed?
    end
  
    private
  
    def downcase_email
      self.email = email.downcase
    end
  end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :require_login  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_lists_helper.rb
module BuyListsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/index.html.erb
<h1 style="text-align: center;">Home Inventory</h1>
<% if current_user.present?  %>
<h2>User Info</h2>
<h2>House</h2>

<p><strong>House ID: </strong></p>
<p><strong>House Member: </strong></p>

<% else %>
<div class="row" style="padding: 1rem" >
<div class="col-md-6 col-sm-12" style="display: flex; justify-content: center" >

<div style="display: flex; justify-content: center; padding: 1rem; flex-direction: column"><%= image_tag "image.png",class: 'img-fluid' %></div>
</div>
<div class="col-md-6 col-sm-12">
<h2>Creating a new Family</h2>
<br />
<%= link_to "New family", new_family_path ,class: "btn btn-primary btn-block"%>
<br />
<h2>Creating a new Account or Sign in</h2>
<br />
<%= link_to "Sign In", login_path, class: "btn btn-secondary btn-block" %>
<br />
<%= link_to "Sign Up", sign_up_path, class: "btn btn-secondary btn-block" %>
</div>
</div>
<% end %>