config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :buy_lists
  resources :feeds
  resources :family_members
  resources :families
  
  #root "inventory#index", :as => "inventory"
  get 'inventory', to: "inventory#index", :as =>'inventory'

  get 'buy_lists', to: "buy_list#index", :as =>'shopping'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get 'members', to: "member#index", :as => 'members'
  get 'feed', to: "feeds#index"
  #get 'new_shopping', to: "shopping#new"
  get 'new_inventory', to: "inventory#new"
  get 'inventory/:item_id/edit', to: "inventory#edit"
  #get 'new_member', to: "member#new"

  patch '/inventory/:item_id/edit', to: 'inventory#update'
  get 'family', to: "family#index"
  get 'members', to: "family_members#index", :as => 'members'
  resources :inventory
  # Defines the root path route ("/")
  root "landing#index"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  get "login", to: "sessions#new"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy_list.rb
class BuyList < ApplicationRecord
end

app/models/current.rb
# app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/family.rb
class Family < ApplicationRecord
    has_many :family_member
    has_many :inventory
end                                         

app/models/family_member.rb
class FamilyMember < ApplicationRecord
    belongs_to :families
    has_one :user
end

app/models/feed.rb
class Feed < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  
    has_secure_password
  
    before_save :downcase_email
  
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
    
    has_many :inventory
    has_many :shopping

    def confirm!
      update_columns(confirmed_at: Time.current)
    end
  
    def confirmed?
      confirmed_at.present?
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
  
    def unconfirmed?
      !confirmed?
    end
  
    private
  
    def downcase_email
      self.email = email.downcase
    end
  end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  include Authentication
  def index
    @inventory = Inventory.all
  end
  def show
    @inventory = Inventory.find_by_item_id(params[:item_id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)


    if @inventory.save
      redirect_to @inventory
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @inventory = Inventory.find_by_item_id(params[:item_id])
  end

  def update
    @inventory = Inventory.find_by_item_id(params[:item_id])

    if @inventory.update(inventory_params)
      redirect_to @inventory
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def inventory_params
      params.require(:inventory).permit(:item_id, :item_name, :item_qty, :item_purchase_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_lists_helper.rb
module BuyListsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventory/_form.html.erb
<%= form_with model: @inventory, url: edit_inventory_path(@inventory), method: :patch do |form| %>
  <div>
    <%= form.label :item_id %><br>
    <%= form.text_field :item_id, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_name %><br>
    <%= form.text_field :item_name, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_qty %><br>
    <%= form.number_field :item_qty, in: 1..20, step: 1, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_purchase_date %><br>
    <%= form.text_field :item_purchase_date, class: "form-control" %>
  </div>
  <br />
  <div>
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/inventory/edit.html.erb
<h1>Edit Inventory</h1>

<%= render "form", inventory: @inventory %>

app/views/inventory/index.html.erb
<h1>Inventory</h1>


<div style="margin-bottom: 5px">
 <%= link_to 'Add', new_inventory_path, class: "btn btn-primary" %>
</div>
    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Item Number</th>
      <th scope="col">Item Name</th>
      <th scope="col">Item Qty</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @inventory.each do |inv| %>
    <tr>
      <th scope="row"><%= inv.item_id %></th>
      <td><%= inv.item_name %></td>
      <td><%= inv.item_qty %></td>
      <td>
        <%= link_to 'Edit',edit_inventory_path(inv.item_id), class: "btn btn-warning" %> 
      </td>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/inventory/new.html.erb
<h1>Add New Inventory</h1>

<%= form_with model: @inventory, url: inventory_path do |form| %>
  <div>
    <%= form.label :item_id %><br>
    <%= form.text_field :item_id, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_name %><br>
    <%= form.text_field :item_name, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_qty %><br>
    <%= form.number_field :item_qty, in: 1..20, step: 1, class: "form-control" %>
  </div>
  <div>
    <%= form.label :item_purchase_date %><br>
    <%= form.text_field :item_purchase_date, class: "form-control" %>
  </div>
  <br />
  <div>
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/inventory/show.html copy.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>

app/views/inventory/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>