config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  resources :buy_lists
  resources :feeds
  resources :family_members
  resources :families
  
  #root "inventory#index", :as => "inventory"
  get 'inventory', to: "inventory#index", :as =>'inventory'

  get 'buy_lists', to: "buy_list#index", :as =>'shopping'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get 'members', to: "member#index", :as => 'members'
  get 'feed', to: "feeds#index"
  #get 'new_shopping', to: "shopping#new"
  get 'new_inventory', to: "inventory#new"
  get 'inventory/:item_id/edit', to: "inventory#edit"
  #get 'new_member', to: "member#new"

  patch '/inventory/:item_id/edit', to: 'inventory#update'
  get 'family', to: "family#index"
  get 'members', to: "family_members#index", :as => 'members'
  resources :inventory
  # Defines the root path route ("/")
  root "landing#index"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  get "login", to: "sessions#new"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy_list.rb
class BuyList < ApplicationRecord
end

app/models/current.rb
# app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/family.rb
class Family < ApplicationRecord
    has_many :family_member
    has_many :inventory
end                                         

app/models/family_member.rb
class FamilyMember < ApplicationRecord
    belongs_to :families
    has_one :user
end

app/models/feed.rb
class Feed < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/shopping.rb
class Shopping < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  
    has_secure_password
  
    before_save :downcase_email
  
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
    
    has_many :inventory
    has_many :shopping

    def confirm!
      update_columns(confirmed_at: Time.current)
    end
  
    def confirmed?
      confirmed_at.present?
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
  
    def unconfirmed?
      !confirmed?
    end
  
    private
  
    def downcase_email
      self.email = email.downcase
    end
  end

app/helpers/buy_lists_helper.rb
module BuyListsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeInventoryV1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
  <!-- As a heading -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

   <%= link_to 'Home Inventory', root_path, class: 'nav-brand app-name' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if current_user.present?  %> 
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Inventory List', inventory_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
    
        <%= link_to 'Shopping List', buy_lists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
         <%= link_to 'Family Member', members_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
         <%= link_to 'Feed', feeds_path, class: 'nav-link' %>
      </li>
    </ul>

<%= link_to "Log Out", logout_path, method: :detroy ,class: "btn btn-danger" %>
  </div>
  <% end %>
</nav>
  <!-- As a heading -->

   <div class="container-fluid" style="padding: 1rem">
    <%= yield %>
   </div>
   <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>